### ISSUE TITLE
New dendro filters

### ISSUE THREAD

**Issue by johanvonboer** [humlab-sead/sead_change_control#257]
These filters were requested by the dendro people:

- [x] types of buildings - I think this can be satisfied by the "construction types" filter, but it is currently broken. (#271)
- [x]  outermost date of rings (#287)
- [x]  estimated felling year (#288)
- [ ]  data-type: density/xfr/tree rings - We do have a data types filter, can it be used for this?
- [ ]  kind of wood: living/dead/source (as sampling context?)
- [ ]  isotopes

**Comment by johanvonboer** [comment]
Sampling context filter has an "Other modern" that needs to be relabeled

**Comment by johanvonboer** [comment]
* Types of buildings cannot be represented by "construction types" since it's too specific. We should look through all the sample group descriptions types and list the unique ones. Because the ones we currently have is an amalgamation of group description types and the sample group name itself. See here for more: https://github.com/humlab-sead/sead_change_control/issues/271

* outermost date of rings - should be straight forward to implement. You can find the dendro_lookup_id 137 in tbl_dendro_dates.

**Comment by johanvonboer** [comment]
data-type: density/xfr/tree rings - We do have a data types filter, can it be used for this?

**Comment by johanvonboer** [comment]
"kind of wood: living/dead/source (as sampling context?)"

implement as a new dendro-only filter

**Comment by johanvonboer** [comment]
Ask Anton about isotopes?

**Comment by johanvonboer** [comment]
We need a RAÄ, and a Lämningsnummer-filter.

**Comment by roger-mahler** [comment]
Related (or duplicate) to #91.

**Comment by roger-mahler** [comment]
Added "Construction purpose" filter (#271).
